"""
Defines constants to be used in the application.
"""

MODEL_ID_CLAUDE_SONNET_37 = 'us.anthropic.claude-3-7-sonnet-20250219-v1:0'
MODEL_ID_NOVA_PREMIER = 'us.amazon.nova-premier-v1:0'
MODEL_ID_NOVA_PRO = 'us.amazon.nova-pro-v1:0'
MODEL_ID_NOVA_MICRO = 'us.amazon.nova-micro-v1:0'

MODEL_PROJECT_MANAGER = MODEL_ID_CLAUDE_SONNET_37
MODEL_BUSINESS_ANALYST = MODEL_ID_NOVA_PREMIER
MODEL_SOFTWARE_ARCHITECT = MODEL_ID_CLAUDE_SONNET_37
MODEL_DEVELOPER = MODEL_ID_CLAUDE_SONNET_37
MODEL_CODE_REVIEWER = MODEL_ID_CLAUDE_SONNET_37
MODEL_UI_DESIGNER = MODEL_ID_NOVA_PREMIER
MODEL_UI_TESTER = MODEL_ID_NOVA_PREMIER
MODEL_MINOR_TASK = MODEL_ID_NOVA_MICRO
